### ISSUE TITLE
Data reception from atecc608 implementation

### ISSUE THREAD

**Issue by yseraf** [helium/gateway-mfr-rs#16]
Reading atecc information with this tool ends with timeout and I'm not sure it's correctly implementing the accesses on the chip regarding read direction at least.

**N.B.:** I'm using the atecc608a instead of the atecc608b, I'm not sure it should change something. 
However, my first question would be has it been tested yet on atecc608b or is it still under development for the following aspects?

After some investigation, it appears Microchip's crypto lib and this tool don't work the same way (my observations with "get info" feature).

**Cryptoauthlib** (custom code following lib samples)
  - wake up with low pulse for >50us on SDA
  - tx get info command: 0x60W, 0x03, 0x07, 0x30, 0x00, 0x00, 0x00, 0x03, 0x5D
  - wait command timing
  - tx reset address counter: 0x60W, 0x00
  - rx polling, receive 0x60R, 0x07 + NAK (not ready)
  - rx polling, receive the result, info : 0x60R, 0x00, 0x00, 0x60, 0x02, 0x80, 0x38
--> I receive 0x00, 0x00, 0x60, 0x02 for the info which is correct for a atecc608a.

**gateway-mfs-rs** (info command)
  - wake up with 0x00 data sent on the bus
  - tx get info command: 0x60W, 0x03, 0x07, 0x30, 0x00, 0x00, 0x00, 0x03, 0x5D
  - wait command timing
  - rx receive the result 0x60R, 0x07 and get stuck here with SCL which continue for a byte and SDA which get low.
--> timeout on the bus, retry for 10 times and error

I tried to change timing and let more time to the atecc but it doesn't seems related to that. 
The cryptoauthlib implements polling while this tool doesn't but my impression is more there is some inconsistent state inside the atecc without the reset address counter command before reading.

While it's maybe due to the atecc608a usage, I'm just pointing this out because it doesn't follow the Microchip code, **calib_execute_command** for example and could probably cause some other issues or instabilities.

Also, I can't find a clear explanation in the atecc's datasheet which would define one solution or the other to be the right one.

Any feedback on that would be appreciated.

**Comment by yseraf** [comment]
Well, modifying your tool to follow the cryptoauthlib doesn't fix the issue. It's probably more related to i2cdev (working solution is based on bare metal).

EDIT: Ok so it seems my i2c bus driver works with SMBus mode which doesn't accept message length more than 32B.
I will investigate more and see if a user space config can handle that.

**Comment by yseraf** [comment]
Well, I have finally a bug in my i2c platform driver (i2c-at91-master). Bug related to DMA and fifo...

**Comment by madninja** [comment]
> Well, I have finally a bug in my i2c platform driver (i2c-at91-master). Bug related to DMA and fifo...

very glad that you found it!
