### ISSUE TITLE
Getting error "timeout waiting for bus free"

### ISSUE THREAD

**Issue by wildloveil** [helium/gateway-mfr-rs#18]
Hi,
When I'm trying to run the gateway_mfr application, I keep getting the following error:
[   80.877565] i2c i2c-0: i2c_pxa: timeout waiting for bus free
[   81.261564] i2c i2c-0: i2c_pxa: timeout waiting for bus free
Although I see the ECC608 device using i2cdetect and pointing the app to the right bus using:
 ./gateway_mfr --device ecc://i2c-0:60?slot=0 info

**Comment by madninja** [comment]
Discussion also started in Discord.. moved there

**Comment by 3nprob** [comment]
@madninja  discord requires phone number so many of us can not follow discussions taking place there.

**Comment by madninja** [comment]
Perhaps @wildloveil can post the resolution once he/she figures out the underlying configuration issue
