### ISSUE TITLE
key programmed with gateway-mfr-rs showing error with gateway-mfr-rs and gateway_mfr

### ISSUE THREAD

**Issue by shawaj** [helium/gateway-mfr-rs#8]
We have some devices which were previously successfully programmed with keys:
```
11G2gWc9ejatoMqJWgLJDRnbtCiG6GQTc8SagAJAhePWCGVnwna
112JUc61GKvnV3m6oRAVJJhafZp9e5hxgMgh9dt3Kn18qnH18hZy
```

However, they now have stopped working, and both gateway-mfr-rs and gateway_mfr show errors with them not being compact keys (before the customer has been able to onboard them)...

```
root@f2bb3b2936d7:/opt/python-dependencies/hm_pyhelper# ./gateway_mfr key 0
Error: decode error

Caused by:
    not a compact key
```

```
root@f2bb3b2936d7:/opt/python-dependencies/hm_pyhelper# ./gateway_mfr config key 0
{
  "key_config": {
    "auth_key": 0,
    "intrusion_disable": false,
    "key_type": "ecc",
    "lockable": true,
    "private": true,
    "pub_info": true,
    "req_auth": false,
    "req_random": false,
    "x509_index": 0
  },
  "slot": 0
}
```

```
root@f2bb3b2936d7:/opt/python-dependencies/hm_pyhelper# ./gateway_mfr info
{
  "info": "00006003",
  "serial": "012373fa15535bc4ee"
}
root@f2bb3b2936d7:/opt/python-dependencies/hm_pyhelper# ./gateway_mfr test
{
  "result": "fail",
  "tests": [
    {
      "output": "ok",
      "result": "pass",
      "test": "serial"
    },
    {
      "output": "ok",
      "result": "pass",
      "test": "zone_locked(data)"
    },
    {
      "output": "ok",
      "result": "pass",
      "test": "zone_locked(config)"
    },
    {
      "output": "ok",
      "result": "pass",
      "test": "slot_config(0..=15, ecc)"
    },
    {
      "output": "ok",
      "result": "pass",
      "test": "key_config(0..=15, ecc)"
    },
    {
      "output": "decode error\n\nCaused by:\n    not a compact key",
      "result": "fail",
      "test": "miner_key(0)"
    },
    {
      "output": "decode error\n\nCaused by:\n    not a compact key",
      "result": "fail",
      "test": "sign(0)"
    },
    {
      "output": "decode error\n\nCaused by:\n    not a compact key",
      "result": "fail",
      "test": "ecdh(0)"
    }
  ]
}
```

```
root@18e6619:/opt/gateway_mfr# /opt/gateway_mfr/bin/gateway_mfr ecc test
+--------------------+-------------------+
|        name        |      result       |
+--------------------+-------------------+
|     serial_num     |        ok         |
|{zone_locked,config}|        ok         |
| {zone_locked,data} |        ok         |
|    slot_config     |        ok         |
|     key_config     |        ok         |
|     miner_key      |{error,not_compact}|
+--------------------+-------------------+
```

Any idea on how to fix this?

**Comment by shawaj** [comment]
in gateway_mfr we have:
```
/opt/gateway_mfr/bin/gateway_mfr ecc provision_onboard
```

is there a similar thing in gateway-mfr-rs?

**Comment by madninja** [comment]
Thanks for the cross-link. That's a long thread so a bit hard to tell what actually _caused_ the issue. The symptom looks like mfr-rs got the ecc to generate a key but that key was not compact and it did not realize this somehow. Alternately this or something other tool or glitch caused a generate command to get sent to the ecc which generated a non compact key in that slot. 

 I'm assuming you're on the latest git ref of the repo. 

The equivalent to `provision_onboard` is to call gateway-mfr-rs with `key --generate <slot>` to generate a new private key in the given slot

**Comment by shawaj** [comment]
Yeah, sorry that thread I linked is somewhat related but was a few different errors manifesting at once so is a bit confusing / unhelpful.

It's a strange one because in manufacturing a key was generated and output to our onboarding server and passed the ECC tests in manufacturing but then somehow once they got to customers they were showing this "not a compact key" error. So it seems either something went wrong in manufacturing and it shouldn't have passed the test then (maybe due to an older version of software perhaps?). Or the ECC subsequently got corrupted somehow 🤔🤔

Not really sure. We've only had it crop up on about half a dozen devices so doesn't seem super prevalent and it's easy to fix, but just wanted to see if it was something we had done wrong or a bug or whatever.

In any case, thanks for the pointer re `key --generate <slot>` that's very useful👍

We have started using gateway-mfr-rs exclusively in manufacturing as of the last few weeks and seems to be working great 🙂

Will close this now

**Comment by madninja** [comment]
> It's a strange one because in manufacturing a key was generated and output to our onboarding server and passed the ECC tests in manufacturing but then somehow once they got to customers they were showing this "not a compact key" error. So it seems either something went wrong in manufacturing and it shouldn't have passed the test then (maybe due to an older version of software perhaps?). Or the ECC subsequently got corrupted somehow 🤔🤔

ECC corruption seems very unlikely but there _definitely_ were older versions of this cli that allowed non compact keys.

**Comment by shawaj** [comment]
Yeah I thought that re the corruption.

Aha.... That probably explains it then. We had previously done some testing with v0.1.2 and 0.1.3
